### ISSUE TITLE
cp: cannot stat '/home/administrator/tmp/research_code/evosoro/_voxcad/voxelyzeMain/voxelyze': No such file or directory chmod: cannot access 'voxelyze': No such file or directory

### ISSUE THREAD

**Issue by thisisjasleen** [skriegman/reconfigurable_organisms#4]

**Comment by tarasio-mirror** [comment]
If I understood correctly the purpose of these lines:
```python
sub.call("cp ~/tmp/research_code/evosoro/_voxcad/voxelyzeMain/voxelyze .", shell=True)
sub.call("chmod 755 voxelyze", shell=True)
```
... is to copy compiled physics engine `voxelize` to the current working directory (from which the example script is running) and then set execution permission (755) for it via `chmod`.

Thus, you need to replace `"cp ~/tmp/research_code/
reconfigurable_organisms /_voxcad/voxelyzeMain/voxelyze ."` with your path to compiled `voxelyze`, for example, if you cloned `reconfigurable_organisms` repo to `home` folder you just need replace first line with this one: 
```python
sub.call("cp ~/reconfigurable_organisms/_voxcad/voxelyzeMain/voxelyze .", shell=True)
```

**Comment by thisisjasleen** [comment]
Thanks a lot, @trsvchn . My issue has been resolved.
