### ISSUE TITLE
Segmentation fault when trying to Open VoxCad

### ISSUE THREAD

**Issue by biagzi** [skriegman/reconfigurable_organisms#7]
Hi,
first: thanks for the Installation instructions.
I've done all the steps described and they have worked. I am using Debian and during the compilation some errors appeared related to not recognize some libraries used. 
I fixed them usually changing the name of the library, based on similar errors and solutions I've found in the internet. After that, it compiled.

But when trying to open VoxCad using the command "./VoxCad", this message appears:
"Segmentation fault" and now I do not know where is the problem and how to fix it.

**Comment by skriegman** [comment]
Check out our new simulator:
https://cdorgs.github.io/code

You can 
`sudo snap install voxcraft-viz`

voxcraft-viz is actually the same voxcad from this repo but with some additional features to play back movies of xenobot behavior.
