### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by indubeetably** [skriegman/reconfigurable_organisms#9]
TypeError when running the Locomotion_pass2 experiment...
<img width="1765" alt="Screen Shot 2021-02-16 at 7 14 03 PM" src="https://user-images.githubusercontent.com/55149355/108138213-77f14e00-708b-11eb-9344-6817e4219611.png">

**Comment by skriegman** [comment]
this is the error you get if networkx is not reverted <2.0

**Comment by indubeetably** [comment]
I see. I tried to ensure networkx is 1.11 by pip installing it again, but no difference. Am I doing something wrong with the reversion  to 1.11?
<img width="1765" alt="Screen Shot 2021-02-16 at 7 45 15 PM" src="https://user-images.githubusercontent.com/55149355/108140167-88a3c300-708f-11eb-87de-c09827e3b035.png">

**Comment by skriegman** [comment]
Networkx 2 might still be in the python path. 

Can you print out `nx.__verison__`  and `nx.__file__` ?

**Comment by indubeetably** [comment]
Yes, like this?:
<img width="1765" alt="Screen Shot 2021-02-16 at 8 41 12 PM" src="https://user-images.githubusercontent.com/55149355/108144360-7d549580-7097-11eb-8e7a-4923c565235f.png">

**Comment by skriegman** [comment]
hmm i'm not sure. can you give me all the details. Every step you took.

and does this repo work?
https://github.com/skriegman/2019-RSS

**Comment by indubeetably** [comment]
Here are the steps I followed, line by line, from installing anaconda to running the script. The main thing I changed was to add a "2" to anaconda in the last command so that it contains 'anaconda2' instead of just 'anaconda':
    1  bash ~/Downloads/Anaconda2-2019.10-Linux-x86_64.sh
    2  conda create --name py27-2019-RSS python=2.7
    3  conda activate py27-2019-RSS
    4  pip install networkx==1.11
    5  sudo apt-get install libqt4-dev qt4-qmake libqwt-dev freeglut3-dev zlib1g-dev
    6  sudo apt-get install git
    7  cd ~
    8  git clone https://github.com/skriegman/2019-RSS
    9  cd 2019-RSS/_voxcad/
   10  ./rebuild_everything.sh
   11  make
   12  cd Voxelyze
   13  make
   14  make installusr
   15  cd ../voxelyzeMain/
   16  make
   17  cd
   18  cd 2019-RSS/evosoro/exp/
   19  PYTHONPATH=$HOME/2019-RSS/ $HOME/anaconda2/bin/python quadrupeds.py 1 1
<img width="1453" alt="Screen Shot 2021-02-16 at 11 56 00 PM" src="https://user-images.githubusercontent.com/55149355/108158286-9c145580-70b2-11eb-8154-cd9d193c8637.png">

**Comment by liusida** [comment]
Sorry, I can't reproduce the error. However, I notice that when you printed the version of the `networkx`, it showed that the package is in the path: `~/anaconda2/envs/py27/lib/python2.7/site-packages/networkx/`; and when you encountered that TypeError, it showed that the package is in the path: `~/anaconda2/lib/python2.7/site-packages/networkx/`. So I guess the error happened because the latter networkx package is 2.x.
I installed the networkx 1.11, and there is no file called `reportviews.py` as well.

Could you check the package again to make sure networkx 1.11 is used?
 Thanks.

**Comment by liusida** [comment]
If I was right, a solution might be:
```
$ ~/anaconda2/bin/python -m pip uninstall networkx
... Successfully uninstalled.
$ ~/anaconda2/bin/python -m pip install networkx==1.11
... Installed.
```
and then try to run it again. So the `networkx` in the base environment will also be `1.11`. (I assumed you don't need networkx 2.x for other applications.)

**Comment by indubeetably** [comment]
That worked...I'll use python -m pip and always try to use an environment for my sanity, lol. And I pointed the subprocess call to a local copy of the evosoro repo...should I not have done that? Thanks 🙏 , gentlemen!
<img width="1633" alt="Screen Shot 2021-02-17 at 12 30 44 PM" src="https://user-images.githubusercontent.com/55149355/108243925-9eab9500-711c-11eb-8f54-7d7bf4b5899d.png">
